services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: always
    networks:
      - net
    depends_on:
      - app_db
  app_db:
    image: postgres:latest
    container_name: app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: any_password
      POSTGRES_DB: any_DB_name
    volumes:
      - database:/var/lib/postgresql/data
      - ./InitDB:/docker-entrypoint-initdb.d/
    networks:
      - net

volumes:
  database:

networks:
  net:
    driver: bridge